DROP TABLE IF EXISTS `flcCOURSES`

CREATE TABLE IF NOT EXISTS `flcCOURSES` (
    `USERID` NOT NULL AUTO_INCREMENT,
    `COURSE` VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (USERID)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=LATIN1;
