DROP TABLE IF EXISTS `flcCOURSES`;

CREATE TABLE IF NOT EXISTS `flcCOURSES` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `USERID` VARCHAR(50) DEFAULT NULL,
    `COURSE` VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (ID)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=LATIN1;
