DROP TABLE IF EXISTS `flcENROLLMENT`;

CREATE TABLE IF NOT EXISTS `flcENROLLMENT` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TRIMESTER` VARCHAR(50) DEFAULT NULL,
  `FULLNAMES` VARCHAR(50) DEFAULT NULL,
  `GENDER` VARCHAR(50) DEFAULT NULL,
  `IDNO` VARCHAR(50) DEFAULT NULL,
  `PLACEOFBIRTH` VARCHAR(50) DEFAULT NULL,
  `DOB` VARCHAR(50) DEFAULT NULL,
  `RESIDENCE` VARCHAR(50) DEFAULT NULL,
  `PROFESSION` VARCHAR(50) DEFAULT NULL,
  `POBOX` VARCHAR(50) DEFAULT NULL,
  `EMAIL` VARCHAR(50) DEFAULT NULL,
  `TELEPHONE` VARCHAR(50) DEFAULT NULL,
  `GUARDIAN` VARCHAR(50) DEFAULT NULL,
  `COURSE` VARCHAR(50) DEFAULT NULL,
  `INTAKE` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=LATIN1;

