DROP TABLE IF EXISTS `flcSCHOLARSHIP`;

CREATE TABLE IF NOT EXISTS `flcSCHOLARSHIP` (
    `USERID` INT(11) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(50) DEFAULT NULL,
    `admissionnum` VARCHAR(50) DEFAULT NULL,
    `Reasons` VARCHAR(50) DEFAULT NULL,
    `Datesubmitted` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`USERID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=LATIN1;
