Intead of DROP use 

ALTER TABLE `flcUSERS` ADD `IDNO` VARCHAR(50) NULL DEFAULT NULL AFTER `DATE`, ADD `COURSE` VARCHAR(50) NULL DEFAULT NULL AFTER `IDNO`;

///

DROP TABLE IF EXISTS `flcUSERS`;

CREATE TABLE IF NOT EXISTS `flcUSERS` (
  `USERID` INT(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(50) DEFAULT NULL,
  `FIRSTNAME` VARCHAR(50) DEFAULT NULL,
  `LASTNAME` VARCHAR(50) DEFAULT NULL,
  `EMAIL` VARCHAR(50) DEFAULT NULL,
  `PHONENUM` VARCHAR(50) DEFAULT NULL,
  `USERTYPE` VARCHAR(50) DEFAULT NULL,
  `PASSWORD` VARCHAR(50) DEFAULT NULL,
  `IDNO` VARCHAR(50) DEFAULT NULL,
  `COURSE` VARCHAR(50) DEFAULT NULL,
  `PROFILEIMG` VARCHAR(50) DEFAULT NULL,
  `DATE` datetime default CURRENT_TIMESTAMP,
  PRIMARY KEY (`USERID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=LATIN1;

INSERT INTO `flcUSERS` (
  `USERID`,
  `USERNAME`,
  `FIRSTNAME`,
  `LASTNAME`,
  `EMAIL`,
  `PHONENUM`,
  `USERTYPE`,
  `IDNO`,
  `COURSE`,
  `PROFILEIMG`,
  `PASSWORD`
) VALUES (
  1,
  'ken',
  'kenedy',
  'cheruiyot',
  'cheruiyotkenedy@gmail.com',
  '0711314358',  
  'Admin',
  ''.
  '',
  '',
  'pass'
),
(
  2,
  'labu',
  'labrador',
  'mwangi',
  'labradorgichohi@gmail.com',
  '0729179309',
  'Admin',
  ''.
  '',
  '',
  'pass'
),(
  3,
  'FLC022026KE',
  'Maureen',
  'Madzo',
  'FLC022026KE',
  '+254741950326',
  'Student',
  ''.
  '',
  '',
  '26211650'
);